version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
    
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '2g'        
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: '2g'   
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  mvn:
  
    image: maven:3.5.4
    volumes:
    - ./:/usr/src/mvn-src
    working_dir: /usr/src/mvn-src
    command: mvn clean  test   -Dselenium-hub.host=hub -Dmaven.wagon.http.ssl.insecure=true
    links:
      [hub,chrome,firefox]
   
